name: Generate Metrics Release

on:
  push:
    branches: [main, develop, id/*]
    tags:
      - "v*"

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 📬 Caching
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.{js,jsx,ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: 🧰 Install dependencies
        run: yarn install

      - name: 🧪 Test and coverage
        run: yarn test --coverage --passWithNoTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  send-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Create Metrics SonarCloud
        run: python metrics/sonar-metrics.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Commit Metrics SonarCloud File
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_USERNAME }}"
          git clone --single-branch --branch main "https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/IanFPFerreira/teste-sonar" doc
          mkdir -p doc/analytics-raw-data
          cp -R fga-eps-mds*.json doc/analytics-raw-data
          cd doc
          git add .
          git commit -m "Métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Metrics File Generated Successfully."